FROM postgres:16-bookworm

RUN apt-get update && \
    apt-get install -y \
    curl \
    sudo \
    vim \
    procps \
    postgresql-16-repmgr \
    && rm -rf /var/lib/apt/lists/*

RUN echo \
    "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown, \
    /usr/bin/openssl, /usr/bin/repmgr, /usr/bin/psql" \
    > /etc/sudoers.d/postgres

COPY --chmod=755 ensure-ssl.sh /usr/local/bin/ensure-ssl.sh
COPY --chmod=755 start.sh /usr/local/bin/start.sh

ENTRYPOINT ["start.sh"]
